### ISSUE TITLE
Show tooltip on click

### ISSUE THREAD

**Issue by juandopazo** [tommoor/HackerNew#14]
Hi! First of all I'd like to say thanks and great job on the latest update! The ability to reach the search box was really necessary.

I really like this extension for various reasons:
1. Almost white background and blue links help readability and usability
2. Reply-on-place is super useful.

That said, something that's always bugged me is that tooltips open on mouseover. I keep opening them when I don't really want to. And they don't close on mouseout! Could you make them open on click, use a time threshold or add the option to change the trigger event?

Thanks!

PS: you missed a pixel here :P
![Captura](https://f.cloud.github.com/assets/347002/251176/4e2bc796-8b5e-11e2-88e1-88963a7757f4.JPG)

**Comment by tommoor** [comment]
Cleaning up this repo, clearly this isn't going to get implemented 😆
