### ISSUE TITLE
Smart auto-collapse comments

### ISSUE THREAD

**Issue by aug-riedinger** [tommoor/HackerNew#27]
Basically, I guess like many users, I want to read most interesting comments first.

Why not going for the following algorithm:

```
Comment #1
  Comment #1.1 
  Comment #1.2
Comment #2 
  Comment #2.1
```

```
if (Score(Comment) > Score(NextParent(Comment))) { 
  #displayed 
} else { 
  #collapsed 
}
# with NextParent(Comment#1.1) = Comment#2
# NextParent(Comment#2.1.3) = Comment#2.2
# etc.
# and Score() from the official formula: https://news.ycombinator.com/item?id=1781013
```

as initial setup and recalculated on every uncollapse event.

I can PR if desired.

**Comment by tommoor** [comment]
I believe HN already does a good job of surfacing the most popular comments and I've now removed the toggling reply logic out of this plugin as they also implemented this themselves.

Closing this for now, but thanks for the idea.
