### ISSUE TITLE
Commenting broken with this extension

### ISSUE THREAD

**Issue by pconerly** [tommoor/HackerNew#28]
Hey, the last few days I haven't been able to comment using this extension. I disabled it and I was able to comment using HN's normal style.

Thanks for the extension, I enjoy it a lot!

**Comment by tommoor** [comment]
Yea, I noticed this too and hand't gotten around to fixing - thanks for the prod.

**Comment by pconerly** [comment]
NP! LMK if you want help testing.

**Comment by bluetidepro** [comment]
It looks like it's something to do with jQuery when I open up the console when trying to comment. Any ETA on this fix?

**Comment by pconerly** [comment]
Thanks for the fix!
