### ISSUE TITLE
Is repo not up to date?

### ISSUE THREAD

**Issue by pconerly** [tommoor/HackerNew#29]
I was investigating the commenting bug a little, and I loaded the unpacked extension. It's on version 1.2.3, but the version in the chrome store is 1.3.0.

@tommoor do you need to push to master or something? Or is this simply an inconsistency in the chrome store?

**Comment by tommoor** [comment]
It looks like this repo isn't upto date and I've since lost the original source when I changed laptops. I'll try and recover it from the chrome webstore this evening and update here...

**Comment by tommoor** [comment]
All upto date now, I've fixed the commenting issue and will publish an extension update soon.
