### ISSUE TITLE
highlighting of followed users broken

### ISSUE THREAD

**Issue by yanowitz** [tommoor/HackerNew#31]
Expected: When I follow a user, I would see future instances of their name styled with an orange background.

Actual: There is no visible difference. If I hover over their name, the tooltip shows I'm following them, but I see no styling differences.

I've tried disabling all my other Chrome extensions except this one, and I'm still seeing this behavior.

If I add the highlight class by hand to an hnuser element, I get the expected highlighting.

I don't remember when this started (stopped!) happening, but it's been at least a few months. Current Chrome is 57.0.2987.133, Mac OS 10.12.4

(Thanks for the extension btw, it's very useful!)

**Comment by tommoor** [comment]
Hey Jason, can you try this:

- Go to HN homepage
- Follow someone
- Refresh
- Do they show as highlighted after refresh?

**Comment by yanowitz** [comment]
Hmmm. They do indeed! Do I need to refollow everyone? Is there a nice JS snippet I can just paste into console? Sorry to be so lazy about this :(

**Comment by tommoor** [comment]
No need to refollow, I think there's just a bug where it doesn't display until you renavigate to the page

**Comment by yanowitz** [comment]
Ah, I have more info.

If I follow the submitter of a post (e.g., https://news.ycombinator.com/item?id=14141190 and click on "alistairSH" [I just picked something on the front page]) and reload, I see that name highlighted.

However, I am not seeing the author of a comment have their name highlighted if I follow them. In fact, I can go to this person's thread listing <https://news.ycombinator.com/threads?id=alistairSH> and nothing is highlighted, but their submission listing has everything highlighted <https://news.ycombinator.com/submitted?id=alistairSH>

I would expect to see comments highlighted as well. I believe they used to be.

Cheers.

**Comment by tommoor** [comment]
Aha!

They probably changed some CSS then, I'll look at that

**Comment by tommoor** [comment]
Just published `1.3.2` to the Chrome store, it should auto-update within the next 24 hours 😄

**Comment by yanowitz** [comment]
thanks. that works!
