### ISSUE TITLE
No longer available :(

### ISSUE THREAD

**Issue by yaaase** [tommoor/HackerNew#33]
I switched computers and to my dismay, this doesn't seem to be available in the chrome store anymore. I love this extension, and have been using it for years. It's hideous reading the regular site again lol. Is there anything I can do to help maintain this?

**Comment by tommoor** [comment]
The extension is maintained but Google pushed it out of the extension store as there is no privacy policy. You can run the extension easily by downloading this repo and then following these instructions to load into chrome:

![image](https://user-images.githubusercontent.com/380914/65062849-cef07200-d931-11e9-95a3-5985ed6142b6.png)

**Comment by yaaase** [comment]
Ah awesome. Thanks! This thing is absolutely necessary :) lmk if you ever do need any help with it, happy to give back if I can!
